<!DOCTYPE html>
<!-- Desarrollo Web en Entorno Servidor -->
<!-- Tema2: Trabajar con bases de datos en PHP -->
<!-- Felipe Rodríguez Gutiérrez -->
<!-- Tarea: 02 Diodos Bank -->
<html>
    
<head>
    <meta charset="utf-8">
    <title>DWES - Tarea 2 - Felipe Rodríguez Gutiérrez</title>
    <link type="text/css" href="estilos.css" rel="stylesheet" />
    <?php include './includes/funciones.inc'; ?>
</head>

<body>
    <h1 class="centrado">TAREA 2: Diodos Bank</h1>
    <h2 class="centrado">Felipe Rodríguez Gutiérrez</h2>